## Plugin Configuration
---
package:
  name: samples
  description: A plugin for viewing samples
  type: iframe
services:
  route:
    routes:
      - path: samples/view/:sampleId/:-sampleVersion
        view: view
        authorization: true
      - path: samples/about
        view: about
        authorization: false
